/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prepos.gui.utilities;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class MySQLPreparator extends javax.swing.JPanel {

    /**
     * Creates new form MySQLPreparator
     */
    DefaultListModel model;
    
    public MySQLPreparator() {
        initComponents();
        initResources();
    }

    public void initResources() {
        model = new DefaultListModel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chFile = new javax.swing.JFileChooser();
        pFiles = new javax.swing.JPanel();
        bAddFile = new javax.swing.JButton();
        bRemoveFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lFiles = new javax.swing.JList();
        pRelation = new javax.swing.JPanel();
        pDictionary = new javax.swing.JPanel();
        pPreview = new javax.swing.JPanel();
        lTableName = new javax.swing.JLabel();
        tTableName = new javax.swing.JTextField();
        pAttributes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAttributes = new javax.swing.JTable();
        bAddAttributes = new javax.swing.JButton();
        bRemoveAttributes = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 500));

        pFiles.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Files"));

        bAddFile.setText("Add File");
        bAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddFileActionPerformed(evt);
            }
        });

        bRemoveFile.setText("Remove File");
        bRemoveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveFileActionPerformed(evt);
            }
        });

        lFiles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lFiles);

        javax.swing.GroupLayout pFilesLayout = new javax.swing.GroupLayout(pFiles);
        pFiles.setLayout(pFilesLayout);
        pFilesLayout.setHorizontalGroup(
            pFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFilesLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pFilesLayout.createSequentialGroup()
                        .addComponent(bAddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRemoveFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(2, 2, 2))
        );
        pFilesLayout.setVerticalGroup(
            pFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFilesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddFile)
                    .addComponent(bRemoveFile)))
        );

        pRelation.setBorder(javax.swing.BorderFactory.createTitledBorder("Relation"));

        javax.swing.GroupLayout pRelationLayout = new javax.swing.GroupLayout(pRelation);
        pRelation.setLayout(pRelationLayout);
        pRelationLayout.setHorizontalGroup(
            pRelationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pRelationLayout.setVerticalGroup(
            pRelationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        pDictionary.setBorder(javax.swing.BorderFactory.createTitledBorder("Dictionary of Variables"));

        pPreview.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));

        javax.swing.GroupLayout pPreviewLayout = new javax.swing.GroupLayout(pPreview);
        pPreview.setLayout(pPreviewLayout);
        pPreviewLayout.setHorizontalGroup(
            pPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pPreviewLayout.setVerticalGroup(
            pPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        lTableName.setText("Table Name:");

        pAttributes.setBorder(javax.swing.BorderFactory.createTitledBorder("Attributes"));

        tbAttributes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attribute", "Type", "Start", "End"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAttributes);
        tbAttributes.getColumnModel().getColumn(0).setResizable(false);
        tbAttributes.getColumnModel().getColumn(1).setResizable(false);
        tbAttributes.getColumnModel().getColumn(2).setResizable(false);
        tbAttributes.getColumnModel().getColumn(3).setResizable(false);

        bAddAttributes.setText("Add Attribute");
        bAddAttributes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddAttributesActionPerformed(evt);
            }
        });

        bRemoveAttributes.setText("Remove Attribute");

        javax.swing.GroupLayout pAttributesLayout = new javax.swing.GroupLayout(pAttributes);
        pAttributes.setLayout(pAttributesLayout);
        pAttributesLayout.setHorizontalGroup(
            pAttributesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addGroup(pAttributesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAddAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRemoveAttributes))
        );
        pAttributesLayout.setVerticalGroup(
            pAttributesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAttributesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAttributesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddAttributes)
                    .addComponent(bRemoveAttributes)))
        );

        javax.swing.GroupLayout pDictionaryLayout = new javax.swing.GroupLayout(pDictionary);
        pDictionary.setLayout(pDictionaryLayout);
        pDictionaryLayout.setHorizontalGroup(
            pDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDictionaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pAttributes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pDictionaryLayout.createSequentialGroup()
                        .addComponent(lTableName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTableName)))
                .addContainerGap())
        );
        pDictionaryLayout.setVerticalGroup(
            pDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDictionaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTableName)
                    .addComponent(tTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pAttributes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pRelation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pDictionary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pDictionary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pRelation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddFileActionPerformed
        int option = chFile.showOpenDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            String path = chFile.getSelectedFile().getAbsolutePath();
            
            model.addElement(path);
            lFiles.setModel(model);
        }
    }//GEN-LAST:event_bAddFileActionPerformed

    private void bRemoveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveFileActionPerformed
        int index = lFiles.getSelectedIndex();
        model.remove(index);
    }//GEN-LAST:event_bRemoveFileActionPerformed

    private void bAddAttributesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddAttributesActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbAttributes.getModel();
        model.addRow(new Object[]{"","",0,0});
    }//GEN-LAST:event_bAddAttributesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddAttributes;
    private javax.swing.JButton bAddFile;
    private javax.swing.JButton bRemoveAttributes;
    private javax.swing.JButton bRemoveFile;
    private javax.swing.JFileChooser chFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lFiles;
    private javax.swing.JLabel lTableName;
    private javax.swing.JPanel pAttributes;
    private javax.swing.JPanel pDictionary;
    private javax.swing.JPanel pFiles;
    private javax.swing.JPanel pPreview;
    private javax.swing.JPanel pRelation;
    private javax.swing.JTextField tTableName;
    private javax.swing.JTable tbAttributes;
    // End of variables declaration//GEN-END:variables
}
